# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:   pretty

# Setup
title:       London Genetics Network
tagline:     ''
description: ''
url:         https://kai-lim.github.io/London_GenNet/
baseurl:     /
lastmod:    '9 November 2021'

author:
  name:      'London Genetics Network'
  url:       https://kai-lim.github.io/London_GenNet/
  email:     londongeneticsnetwork@gmail.com
  twitter: LdnGeneNet

pagination:
  indexpage: 'blog'

# Plugins
plugins: ['jekyll-twitter-plugin']